### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by chqrqkter** [jayb-g/bbrem2sn#1]
Hi you! 
I saw your comment about Github Android client, I don't know if I understood correctly that you were looking for yourself and OctoDroid is the best for you.
I had the same problem to find something suitable, theoretically OctoDroid could also be on my number 1 but to save your time and if I just understood it correctly I recommend to check two more, maybe 3 is just as good!
the first, pretty and her own because of her writes because I found her at once only long

- DioHub - writes her own.
- Gloom Material (but debug version to do.)

ia I tried to do FastHub-RE for myself by AndroidIDE because it is also great but old. unfortunately hard because a lot of dependencies and libraries.

sorry to write here but I don't know if and where you can private 💁🤪

**good luck! **

**Comment by jayb-g** [comment]
👍 Thanks
